import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import { SanityLive } from "../../sanity/lib/live"

const inter = Inter({  
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased  min-h-[125vh]`}
      >
        <SanityLive />
        {children}
        
      </body>
    </html>
  );
}

export default RootLayout;